// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoDefaultsPolicy) DeepCopyInto(out *NoDefaultsPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoDefaultsPolicy.
func (in *NoDefaultsPolicy) DeepCopy() *NoDefaultsPolicy {
	if in == nil {
		return nil
	}
	out := new(NoDefaultsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NoDefaultsPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoDefaultsPolicyList) DeepCopyInto(out *NoDefaultsPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NoDefaultsPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoDefaultsPolicyList.
func (in *NoDefaultsPolicyList) DeepCopy() *NoDefaultsPolicyList {
	if in == nil {
		return nil
	}
	out := new(NoDefaultsPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NoDefaultsPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoDefaultsPolicySpec) DeepCopyInto(out *NoDefaultsPolicySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoDefaultsPolicySpec.
func (in *NoDefaultsPolicySpec) DeepCopy() *NoDefaultsPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NoDefaultsPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoDefaultsPolicyStatus) DeepCopyInto(out *NoDefaultsPolicyStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoDefaultsPolicyStatus.
func (in *NoDefaultsPolicyStatus) DeepCopy() *NoDefaultsPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NoDefaultsPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
